dataset_name: glass_identification
model_hyperparameters:
  activation: relu
  alpha: 0.0001
  batch_size: auto
  beta_1: 0.9
  beta_2: 0.999
  early_stopping: false
  epsilon: 1.0e-08
  hidden_layer_sizes: !!python/tuple
  - 100
  learning_rate: constant
  learning_rate_init: 0.001
  max_fun: 15000
  max_iter: 1000
  momentum: 0.9
  n_iter_no_change: 10
  nesterovs_momentum: true
  power_t: 0.5
  random_state: 42
  shuffle: true
  solver: adam
  tol: 0.0001
  validation_fraction: 0.1
  verbose: false
  warm_start: false
model_name: MLP
model_type: MLPClassifier
scaling_name: StandardScaler
