dataset_name: breast_cancer_wisconsin_diagnostic
model_hyperparameters:
  cat_dims: []
  cat_emb_dim: []
  cat_idxs: []
  clip_value: 1
  device_name: auto
  epsilon: 1.0e-15
  gamma: 1.3
  grouped_features: []
  input_dim: 30
  lambda_sparse: 0.001
  mask_type: sparsemax
  momentum: 0.02
  n_a: 8
  n_d: 8
  n_indep_decoder: 1
  n_independent: 2
  n_shared: 2
  n_shared_decoder: 1
  n_steps: 3
  optimizer_fn: !!python/name:torch.optim.adam.Adam ''
  optimizer_params:
    lr: 0.02
  output_dim: 2
  scheduler_fn: null
  scheduler_params: {}
  seed: 42
  verbose: 1
model_name: TabNet
model_type: TabNetClassifier
scaling_name: TanhTransformer
