dataset_name: breast_cancer_wisconsin_diagnostic
model_hyperparameters:
  base_score: null
  booster: null
  callbacks: null
  colsample_bylevel: null
  colsample_bynode: null
  colsample_bytree: null
  device: null
  early_stopping_rounds: null
  enable_categorical: false
  eval_metric: null
  feature_types: null
  feature_weights: null
  gamma: null
  grow_policy: null
  importance_type: null
  interaction_constraints: null
  learning_rate: null
  max_bin: null
  max_cat_threshold: null
  max_cat_to_onehot: null
  max_delta_step: null
  max_depth: null
  max_leaves: null
  min_child_weight: null
  missing: .nan
  monotone_constraints: null
  multi_strategy: null
  n_estimators: null
  n_jobs: null
  num_parallel_tree: null
  objective: binary:logistic
  random_state: null
  reg_alpha: null
  reg_lambda: null
  sampling_method: null
  scale_pos_weight: null
  subsample: null
  tree_method: null
  validate_parameters: null
  verbosity: null
model_name: XGBoost
model_type: XGBClassifier
scaling_name: VariableStabilityScaling
